import { StyleSheet, Platform } from 'react-native';
import {
  Color,
  Border,
  Padding,
  FontSize,
  FontFamily,
} from '../../../GlobalStyles';

const styles = StyleSheet.create({
  background: {
    left: -100,
  },
  backgroundLayout: {
    opacity: 0.3,
    transform: [
      {
        rotate: '-37.93deg',
      },
    ],
    height: 250,
    width: 340,
    top: -90,
    backgroundColor: Color.baseColorGreyLight,
    borderBottomLeftRadius: Border.br_31xl,
    borderBottomRightRadius: Border.br_31xl,
    position: 'absolute',
  },
  backgroundLayout2: {
    opacity: 0.3,
    transform: [
      {
        rotate: '136.93deg',
      },
    ],
    height: 250,
    width: 340,
    top: 610,
    backgroundColor: Color.baseColorGreyLight,
    borderBottomLeftRadius: Border.br_31xl,
    borderBottomRightRadius: Border.br_31xl,
    position: 'absolute',
  },
  background2: {
    right: -120,
  },
  containerFlexBox: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  labelTypo: {
    height: 29,
    textAlign: 'left',
    lineHeight: 16,
    fontSize: FontSize.fontsPSmall_size,
    display: 'flex',
    fontFamily: FontFamily.fontsH5,
  },
  placeholdTypo: {
    height: 18,
    lineHeight: 18,
    fontSize: FontSize.fontsP_size,
    display: 'flex',
    textAlign: 'left',
    color: Color.textColorGrey,
    fontFamily: FontFamily.fontsH5,
    alignItems: 'center',
    overflow: 'hidden',
  },
  inputShadowBox: {
    padding: Padding.p_base,
    marginTop: 4,
    flexDirection: 'row',
    height: 45,
    borderWidth: 1,
    borderColor: '#eee',
    borderStyle: 'solid',
    shadowOpacity: 1,
    elevation: 4,
    shadowRadius: 4,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    backgroundColor: Color.baseColorWhite,
    borderRadius: Border.br_7xs,
    overflow: 'hidden',
  },
  inputLayout: {
    width: 145,
    alignItems: 'center',
  },
  buttonLayout: {
    height: 35,
    width: 254,
    paddingTop: 6,
  },
  navFlexBox: {
    padding: Padding.p_8xs,
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonFlexBox: {
    display: 'flex',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  background1: {
    top: -172,
    left: 156,
  },
  walletTest: {
    fontSize: FontSize.fontsH1_size,
    lineHeight: 32,
    textAlign: 'center',
    color: Color.baseColorWhite,
    fontFamily: FontFamily.fontsH3,
    alignSelf: 'stretch',
    paddingBottom: 15,
  },
  label: {
    width: 310,
    alignItems: 'center',
    color: Color.textColorGrey,
  },
  icons8oldTimeCamera: {
    width: 32,
    height: 32,
    overflow: 'hidden',
  },
  placehold: {
    width: 243,
    marginLeft: 10,
  },
  input: {
    paddingLeft: Padding.p_3xs,
    paddingTop: Padding.p_base,
    paddingRight: Padding.p_base,
    paddingBottom: Padding.p_base,
    marginTop: 4,
    height: 45,
    borderWidth: 1,
    borderColor: 'white',
    borderStyle: 'solid',
    shadowOpacity: 1,
    elevation: 4,
    shadowRadius: 4,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    backgroundColor: Color.baseColorWhite,
    borderRadius: Border.br_7xs,
    flexDirection: 'row',
    width: 310,
    alignItems: 'center',
    overflow: 'hidden',
  },
  animationWalletbtninputLab: {
    marginTop: 10,
    padding: Padding.p_7xs,
  },
  label1: {
    width: 310,
    alignItems: 'center',
    color: Color.baseColorWhite,
    height: 29,
    textAlign: 'left',
    lineHeight: 16,
    fontSize: FontSize.fontsPSmall_size,
  },
  placehold1: {
    width: 280,
  },
  input1: {
    width: 310,
    alignItems: 'center',
  },
  label2: {
    height: 29,
    textAlign: 'left',
    lineHeight: 16,
    fontSize: FontSize.fontsPSmall_size,
    display: 'flex',
    fontFamily: FontFamily.fontsH5,
    color: Color.baseColorWhite,
  },
  placehold2: {
    top: 14,
    left: 16,
    width: 115,
    zIndex: 0,
    position: 'absolute',
    height: 18,
    lineHeight: 18,
    fontSize: FontSize.fontsP_size,
  },
  input2: {
    padding: Padding.p_base,
    marginTop: 4,
    flexDirection: 'row',
    height: 45,
    borderWidth: 1,
    borderColor: '#eee',
    borderStyle: 'solid',
    shadowOpacity: 1,
    elevation: 4,
    shadowRadius: 4,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    backgroundColor: Color.baseColorWhite,
    borderRadius: Border.br_7xs,
    overflow: 'hidden',
  },
  animationWalletbtninputLab2: {
    padding: Padding.p_7xs,
  },
  input3: {
    padding: Padding.p_base,
    marginTop: 4,
    flexDirection: 'row',
    height: 45,
    borderWidth: 1,
    borderColor: '#eee',
    borderStyle: 'solid',
    shadowOpacity: 1,
    elevation: 4,
    shadowRadius: 4,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    backgroundColor: Color.baseColorWhite,
    borderRadius: Border.br_7xs,
    overflow: 'hidden',
  },
  div2Label: {
    flexDirection: 'row',
    marginTop: 10,
    alignSelf: 'stretch',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonDisabled: {
    fontSize: FontSize.fontsH5_size,
    lineHeight: 20,
    display: 'flex',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    color: Color.textColorGrey,
    fontFamily: FontFamily.fontsH5,
    width: 254,
    left: 0,
    top: 0,
    position: 'absolute',
  },
  buttonEnabled: {
    fontSize: FontSize.fontsH5_size,
    lineHeight: 20,
    display: 'flex',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: FontFamily.fontsH5,
    width: 254,
    color: Color.baseColorWhite,
    left: 0,
    top: 0,
    position: 'absolute',
  },
  btnDisabled: {
    borderRadius: Border.br_xs,
    width: 300,
    paddingHorizontal: Padding.p_xl,
    marginTop: 10,
    justifyContent: 'center',
    paddingVertical: Padding.p_3xs,
    alignItems: 'center',
    backgroundColor: Color.baseColorGreyLight,
  },
  btnEnable: {
    borderRadius: Border.br_xs,
    backgroundColor: Color.baseColorBlueLight,
    width: 300,
    paddingHorizontal: Padding.p_xl,
    marginTop: 10,
    justifyContent: 'center',
    paddingVertical: Padding.p_3xs,
    alignItems: 'center',
  },
  container: {
    paddingBottom: 70,
    justifyContent: 'center',
    paddingVertical: Padding.p_3xs,
    alignItems: 'center',
    paddingHorizontal: Padding.p_base,
    height: 800,
  },
  icon: {
    height: '100%',
    width: '100%',
  },
  btnBack: {
    width: 39,
    height: 39,
  },
  cadastro: {
    fontSize: FontSize.fontsH3_size,
    lineHeight: 24,
    color: Color.baseColorBlueLight,
    width: 264,
    display: 'flex',
    fontFamily: FontFamily.fontsH3,
    alignSelf: 'stretch',
    overflow: 'hidden',
  },
  titleHeader: {
    width: 225,
    height: 34,
    marginLeft: 22,
    justifyContent: 'center',
  },
  nav: {
    width: 328,
  },
  header: {
    height: 54,
    justifyContent: 'center',
    top: Platform.OS === 'ios' ? 15 : 0,
  },
  container1: {
    height: 66,
    justifyContent: 'center',
    paddingVertical: Padding.p_3xs,
    alignItems: 'center',
    paddingHorizontal: Padding.p_base,
    width: 360,
    left: 0,
    top: 0,
    position: 'absolute',
  },
  walletCadastro01: {
    backgroundColor: Color.baseColorBlueDark,
    flex: 1,
    overflow: 'hidden',
    height: 800,
    width: '100%',
  },
});

export default styles;
